name: 'Checkout and monorepo install'
description: 'This action checks out the commit, sets up Node and installs deps using lerna.'
author: 'yoobic'
inputs:
  fetch-depth:
    required: false
    description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
    default: '1'
  token:
    required: false
    description: 'Personal access token (PAT) used to fetch the repository.'
    default: ${{ github.token }}
  gcp_credentials:
    required: false
    description: 'The google credentials'
  include_master:
    required: false
    description: 'Include also master branch in order to do incremental test only on changes'
    default: 'false'
  install:
    required: false
    description: 'If true will yarn boostrap'
    default: 'true'
  build:
    required: false
    description: 'If true will run yarn build'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout master
      if: ${{ inputs.include_master == 'true' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        ref: master

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}

    - name: Google authentication
      uses: google-github-actions/auth@v0.4.0
      if: ${{ inputs.gcp_credentials }}
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Setting up the execution env
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key:  node_modules-${{ github.ref_name }}-${{ hashFiles('./yarn.lock') }}
        restore-keys: |
          node_modules-${{ github.ref_name  }}-
          node_modules-master-
          node_modules-main
          node_modules-

    - name: Configure gcp artifact
      if: ${{ inputs.gcp_credentials }}
      run: npx google-artifactregistry-auth@3.0.0
      shell: bash

    - name: Install dependencies
      if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' && inputs.install == 'true' }}
      run: yarn bootstrap
      shell: bash

    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: yarn build
      shell: bash
