name: 'Publish npm package to google artifacts'
description: 'This action checks out the commit, and publish the npm package to google artifacts.'
author: 'yoobic'
inputs:
    fetch-depth:
        required: false
        description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
        default: '1'
    token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
    gcp_credentials:
        required: true
        description: 'The google credentials'
    image:
        required: true
        description: 'The name of the image'
    region:
        required: false
        description: 'The google region'
        default: europe-west1
    registry:
        required: false
        description: 'The name of the artifact registry'
        default: yoobic-docker-images      
runs:
    using: 'composite'
    steps:

        - id: auth
          uses: google-github-actions/auth@v0.4.0
          with:
            credentials_json: ${{ inputs.gcp_credentials }}
        
        - name: Checkout and npm
          uses: yoobic/test-github-action/.github/actions/checkout-and-npm@master

      
        - name: Authorize npm registry
          shell: bash
          run: npx google-artifactregistry-auth 

       
        - name: Publish to npm
          shell: bash
          run: npm publish
        
      