name: 'Checkout and npm install'
description: 'This action checks out the commit, sets up Node and installs deps using npm.'
author: 'yoobic'
inputs:
  fetch-depth:
    required: false
    description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
    default: '1'
  token:
    required: false
    description: 'Personal access token (PAT) used to fetch the repository.'
    default: ${{ github.token }}
  gcp_credentials:
    required: false
    description: 'The google credentials'
  include_master:
    required: false
    description: 'Include also master branch in order to do incremental test only on changes'
    default: 'false'
  ref:
    required: false
    description: 'Replace ref'
  install:
    required: false
    description: 'If true will run npm install'
    default: 'true'
  build:
    required: false
    description: 'If true will run npm run build'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout master
      if: ${{ inputs.include_master == 'true' }}
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        ref: master

    - name: Checkout
      if: ${{ !inputs.ref }}
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        persist-credentials: false
    
    - name: Checkout
      if: ${{ inputs.ref }}
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        persist-credentials: false
        ref: ${{ inputs.ref }}
    
      
    - name: Google authentication
      uses: google-github-actions/auth@v0.4.0
      if: ${{ inputs.gcp_credentials }}
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Setting up the execution env
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'


    - name: Cache node_modules
      id: cache-node
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key:  node_modules-${{ github.ref_name }}-${{ hashFiles('./package-lock.json') }}
        restore-keys: |
          node_modules-${{ github.ref_name  }}-
          node_modules-master-
          node_modules-main
          node_modules-

    - name: Configure gcp artifact
      if: ${{ inputs.gcp_credentials }}
      run: npx google-artifactregistry-auth
      shell: bash

    # We only skip the install path if there is an exact cache hit. If not we restored the not exact cahce so we run an npm install again
    - name: Install dependencies
      if: ${{ steps.cache-node.outputs.cache-hit != 'true' && inputs.install == 'true' }}
      run: npm install 
      shell: bash

    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: npm run build --if-present
      shell: bash
