name: 'Checkout and npm install'
description: 'This action checks out the commit, sets up Node and installs deps using npm.'
author: 'yoobic'
inputs:
  fetch-depth:
    required: false
    description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
    default: '1'
  token:
    required: false
    description: 'Personal access token (PAT) used to fetch the repository.'
    default: ${{ github.token }}
  gcp_credentials:
    required: false
    description: 'The google credentials'
  include_master:
    required: false
    description: 'Include also master branch in order to do incremental test only on changes'
    default: 'false'
  install:
    required: false
    description: 'If true will run npm install'
    default: 'true'
  build:
    required: false
    description: 'If true will run npm run build'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout master
      if: ${{ inputs.include_master == 'true' }}
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        ref: master

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        persist-credentials: false

    - name: Google authentication
      uses: google-github-actions/auth@v0.4.0
      if: ${{ inputs.gcp_credentials }}
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Setting up the execution env
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Get npm cache directory
      id: npm-cache-dir 
      run: echo "::set-output name=dir::$(npm config get cache)"
      shell: bash

    - name: Create cache package file
      run: cp package-lock.json package-lock.cache.json && sed -i 1,3d package-lock.cache.json
      shell: bash

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: modules-${{ hashFiles('package-lock.cache.json') }}

    - name: Cache pulumi
      id: cache-pulumi
      uses: actions/cache@v2
      with:
        path: ~/.pulumi
        key: pulumi-${{ hashFiles('package-lock.cache.json') }}

    - name: Cache eslint
      id: cache-eslint
      uses: actions/cache@v2
      with:
        path: ./.eslintcache
        key: eslint-
        restore-keys: eslint-

    - name: Configure gcp artifact
      if: ${{ inputs.gcp_credentials }}
      run: npx google-artifactregistry-auth
      shell: bash

    - name: Install dependencies
      if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' && inputs.install == 'true' }}
      run: npm install # ci --ignore-script
      shell: bash

    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: npm run build --if-present
      shell: bash
